"""
This file has been auto-generated by pydantic.
TODO: Maybe some fields should be renamed or the architecture should be changed a bit
"""

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Challenges(BaseModel):
    field_12AssistStreakCount: Optional[int] = Field(..., alias='12AssistStreakCount')
    abilityUses: Optional[int] = None
    acesBefore15Minutes: Optional[int] = None
    alliedJungleMonsterKills: Optional[float] = None
    baronBuffGoldAdvantageOverThreshold: Optional[int] = None
    baronTakedowns: Optional[int] = None
    blastConeOppositeOpponentCount: Optional[int] = None
    bountyGold: Optional[int] = None
    buffsStolen: Optional[int] = None
    completeSupportQuestInTime: Optional[int] = None
    controlWardTimeCoverageInRiverOrEnemyHalf: Optional[float] = None
    controlWardsPlaced: Optional[int] = None
    damagePerMinute: Optional[float] = None
    damageTakenOnTeamPercentage: Optional[float] = None
    dancedWithRiftHerald: Optional[int] = None
    deathsByEnemyChamps: Optional[int] = None
    dodgeSkillShotsSmallWindow: Optional[int] = None
    doubleAces: Optional[int] = None
    dragonTakedowns: Optional[int] = None
    earliestBaron: Optional[float] = None
    effectiveHealAndShielding: Optional[float] = None
    elderDragonKillsWithOpposingSoul: Optional[int] = None
    elderDragonMultikills: Optional[int] = None
    enemyChampionImmobilizations: Optional[int] = None
    enemyJungleMonsterKills: Optional[float] = None
    epicMonsterKillsNearEnemyJungler: Optional[int] = None
    epicMonsterKillsWithin30SecondsOfSpawn: Optional[int] = None
    epicMonsterSteals: Optional[int] = None
    epicMonsterStolenWithoutSmite: Optional[int] = None
    firstTurretKilledTime: Optional[float] = None
    flawlessAces: Optional[int] = None
    fullTeamTakedown: Optional[int] = None
    gameLength: Optional[float] = None
    getTakedownsInAllLanesEarlyJungleAsLaner: Optional[int] = None
    goldPerMinute: Optional[float] = None
    hadAfkTeammate: Optional[int] = None
    hadOpenNexus: Optional[int] = None
    highestCrowdControlScore: Optional[int] = None
    immobilizeAndKillWithAlly: Optional[int] = None
    initialBuffCount: Optional[int] = None
    initialCrabCount: Optional[int] = None
    jungleCsBefore10Minutes: Optional[float] = None
    junglerKillsEarlyJungle: Optional[int] = None
    junglerTakedownsNearDamagedEpicMonster: Optional[int] = None
    kTurretsDestroyedBeforePlatesFall: Optional[int] = None
    kda: Optional[float] = None
    killAfterHiddenWithAlly: Optional[int] = None
    killParticipation: Optional[float] = None
    killedChampTookFullTeamDamageSurvived: Optional[int] = None
    killsNearEnemyTurret: Optional[int] = None
    killsOnLanersEarlyJungleAsJungler: Optional[int] = None
    killsOnOtherLanesEarlyJungleAsLaner: Optional[int] = None
    killsOnRecentlyHealedByAramPack: Optional[int] = None
    killsUnderOwnTurret: Optional[int] = None
    killsWithHelpFromEpicMonster: Optional[int] = None
    knockEnemyIntoTeamAndKill: Optional[int] = None
    landSkillShotsEarlyGame: Optional[int] = None
    laneMinionsFirst10Minutes: Optional[int] = None
    legendaryCount: Optional[int] = None
    lostAnInhibitor: Optional[int] = None
    maxKillDeficit: Optional[int] = None
    moreEnemyJungleThanOpponent: Optional[float] = None
    multiKillOneSpell: Optional[int] = None
    multiTurretRiftHeraldCount: Optional[int] = None
    multikills: Optional[int] = None
    multikillsAfterAggressiveFlash: Optional[int] = None
    mythicItemUsed: Optional[int] = None
    outerTurretExecutesBefore10Minutes: Optional[int] = None
    outnumberedKills: Optional[int] = None
    outnumberedNexusKill: Optional[int] = None
    perfectDragonSoulsTaken: Optional[int] = None
    perfectGame: Optional[int] = None
    pickKillWithAlly: Optional[int] = None
    poroExplosions: Optional[int] = None
    quickCleanse: Optional[int] = None
    quickFirstTurret: Optional[int] = None
    quickSoloKills: Optional[int] = None
    riftHeraldTakedowns: Optional[int] = None
    saveAllyFromDeath: Optional[int] = None
    scuttleCrabKills: Optional[int] = None
    skillshotsDodged: Optional[int] = None
    skillshotsHit: Optional[int] = None
    snowballsHit: Optional[int] = None
    soloBaronKills: Optional[int] = None
    soloKills: Optional[int] = None
    soloTurretsLategame: Optional[int] = None
    stealthWardsPlaced: Optional[int] = None
    survivedSingleDigitHpCount: Optional[int] = None
    survivedThreeImmobilizesInFight: Optional[int] = None
    takedownOnFirstTurret: Optional[int] = None
    takedowns: Optional[int] = None
    takedownsAfterGainingLevelAdvantage: Optional[int] = None
    takedownsBeforeJungleMinionSpawn: Optional[int] = None
    takedownsFirst25Minutes: Optional[int] = None
    takedownsInAlcove: Optional[int] = None
    takedownsInEnemyFountain: Optional[int] = None
    teamBaronKills: Optional[int] = None
    teamDamagePercentage: Optional[float] = None
    teamElderDragonKills: Optional[int] = None
    teamRiftHeraldKills: Optional[int] = None
    threeWardsOneSweeperCount: Optional[int] = None
    tookLargeDamageSurvived: Optional[int] = None
    turretPlatesTaken: Optional[int] = None
    turretTakedowns: Optional[int] = None
    turretsTakenWithRiftHerald: Optional[int] = None
    twentyMinionsIn3SecondsCount: Optional[int] = None
    unseenRecalls: Optional[int] = None
    visionScorePerMinute: Optional[float] = None
    wardTakedowns: Optional[int] = None
    wardTakedownsBefore20M: Optional[int] = None
    wardsGuarded: Optional[int] = None
    earliestDragonTakedown: Optional[float] = None
    teleportTakedowns: Optional[int] = None
    earlyLaningPhaseGoldExpAdvantage: Optional[float] = None
    highestWardKills: Optional[int] = None
    laningPhaseGoldExpAdvantage: Optional[float] = None
    maxCsAdvantageOnLaneOpponent: Optional[float] = None
    maxLevelLeadLaneOpponent: Optional[int] = None
    visionScoreAdvantageLaneOpponent: Optional[float] = None
    highestChampionDamage: Optional[int] = None
    fasterSupportQuestCompletion: Optional[int] = None


class StatPerks(BaseModel):
    defense: int
    flex: int
    offense: int


class Selection(BaseModel):
    perk: int
    var1: int
    var2: int
    var3: int


class Style(BaseModel):
    description: str
    selections: List[Selection]
    style: int


class Perks(BaseModel):
    statPerks: StatPerks
    styles: List[Style]


class Participant(BaseModel):
    assists: int
    baronKills: Optional[int] = None
    bountyLevel: Optional[int] = None
    challenges: Optional[Challenges] = None
    champExperience: Optional[int] = None
    champLevel: int
    championId: int
    championName: Optional[str] = None
    championTransform: Optional[int] = None
    consumablesPurchased: Optional[int] = None
    damageDealtToBuildings: Optional[int] = None
    damageDealtToObjectives: int
    damageDealtToTurrets: int
    damageSelfMitigated: int
    deaths: int
    detectorWardsPlaced: Optional[int] = None
    doubleKills: int
    dragonKills: Optional[int] = None
    firstBloodAssist: bool
    firstBloodKill: bool
    firstTowerAssist: bool
    firstTowerKill: bool
    gameEndedInEarlySurrender: Optional[bool] = None
    gameEndedInSurrender: Optional[bool] = None
    goldEarned: int
    goldSpent: int
    individualPosition: Optional[str] = None
    inhibitorKills: int
    inhibitorTakedowns: Optional[int] = None
    inhibitorsLost: Optional[int] = None
    item0: int
    item1: int
    item2: int
    item3: int
    item4: int
    item5: int
    item6: int
    itemsPurchased: Optional[int] = None
    killingSprees: int
    kills: int
    lane: str
    largestCriticalStrike: int
    largestKillingSpree: int
    largestMultiKill: int
    longestTimeSpentLiving: int
    magicDamageDealt: int
    magicDamageDealtToChampions: int
    magicDamageTaken: int
    neutralMinionsKilled: int
    nexusKills: Optional[int] = None
    nexusLost: Optional[int] = None
    nexusTakedowns: Optional[int] = None
    objectivesStolen: Optional[int] = None
    objectivesStolenAssists: Optional[int] = None
    participantId: int
    pentaKills: int
    perks: Optional[Perks] = None  # FIXME: Optional because idk how to transform v4 to v5 perks
    physicalDamageDealt: int
    physicalDamageDealtToChampions: int
    physicalDamageTaken: int
    profileIcon: int
    quadraKills: int
    riotIdName: Optional[str] = None
    riotIdTagline: Optional[str] = None
    role: str
    sightWardsBoughtInGame: int
    spell1Casts: Optional[int] = None
    spell1Id: int
    spell2Casts: Optional[int] = None
    spell2Id: int
    spell3Casts: Optional[int] = None
    spell4Casts: Optional[int] = None
    summoner1Casts: Optional[int] = None
    summoner2Casts: Optional[int] = None
    summonerId: Optional[int] = None
    summonerLevel: Optional[int] = None
    summonerName: str
    teamEarlySurrendered: Optional[bool] = None
    teamId: int
    teamPosition: Optional[str] = None
    timeCCingOthers: int
    timePlayed: Optional[int] = None
    totalDamageDealt: int
    totalDamageDealtToChampions: int
    totalDamageShieldedOnTeammates: Optional[int] = None
    totalDamageTaken: int
    totalHeal: int
    totalHealsOnTeammates: Optional[int] = None
    totalMinionsKilled: int
    totalTimeCCDealt: int
    totalTimeSpentDead: Optional[int] = None
    totalUnitsHealed: int
    tripleKills: int
    trueDamageDealt: int
    trueDamageDealtToChampions: int
    trueDamageTaken: int
    turretKills: int
    turretTakedowns: Optional[int] = None
    turretsLost: Optional[int] = None
    unrealKills: int
    visionScore: int
    visionWardsBoughtInGame: int
    wardsKilled: int
    wardsPlaced: int
    win: bool


class Ban(BaseModel):
    championId: int
    pickTurn: int


class Baron(BaseModel):
    first: bool
    kills: int


class Champion(BaseModel):
    first: bool
    kills: int


class Dragon(BaseModel):
    first: bool
    kills: int


class Inhibitor(BaseModel):
    first: bool
    kills: int


class RiftHerald(BaseModel):
    first: bool
    kills: int


class Tower(BaseModel):
    first: bool
    kills: int


class Objectives(BaseModel):
    baron: Baron
    champion: Optional[Champion] = None
    dragon: Dragon
    inhibitor: Inhibitor
    riftHerald: RiftHerald
    tower: Tower


class Team(BaseModel):
    bans: List[Ban]
    objectives: Objectives
    teamId: int
    win: bool


class GameDetails(BaseModel):
    gameCreation: int
    gameDuration: int
    gameEndTimestamp: Optional[int] = None
    gameId: int
    gameMode: str
    gameName: Optional[str] = None
    gameStartTimestamp: Optional[int] = None
    gameType: str
    gameVersion: str
    mapId: int
    participants: List[Participant]
    platformId: str
    queueId: int
    seasonId: int
    teams: List[Team]
    tournamentCode: Optional[str] = None
